### ISSUE TITLE
Won't build, binaries available?

### ISSUE THREAD

**Issue by callanrocks** [MaxReimann/video-stream-consistency#2]
A few of us having been trying to give this a go, but we've been unable to get it to build for many strange reason we've been unable to get it to successfully build.

Would it be possible for you to release binaries? Thank you.

**Comment by callanrocks** [comment]
We got it built! But it's just throwing segfaults.

**Comment by maxxar92** [comment]
Great, what errors did you encounter previously while building and which OS are you on? If you can provide a stacktrace that would be very helpful, I'll try to find time to look into the issue

**Comment by MaxReimann** [comment]
Great, what errors did you encounter previously while building and which OS are you on? If you can provide a stacktrace that would be very helpful, I'll try to find time to look into the issue

**Comment by callanrocks** [comment]
We've been building across WSL, Ubuntu and a docker environment that we found worked. Which was pytorch/pytorch:2.0.1-cuda11.7-cudnn8-devel.

The one who got furthest building before switching to docker thought it might be related to the ffmpeg version from this error.

`[ 34%] Building CXX object CMakeFiles/FlowVideoConsistency.dir/src/decoding/ffmpeg.cpp.o
/usr/bin/c++ -DD_NMP_ASSET_DIR="R\"(models)\"" -DQT_CORE_LIB -DQT_GUI_LIB -DQT_NO_DEBUG -DQT_WIDGETS_LIB -I/home/user/Schreibtisch/video-stream-consistency/build -I/home/user/Schreibtisch/video-stream-consistency -I/home/user/Schreibtisch/video-stream-consistency/build/FlowVideoConsistency_autogen/include -I/home/user/Schreibtisch/video-stream-consistency/src -I/home/user/Schreibtisch/video-stream-consistency/src/ort_custom_ops/include -isystem /home/user/Schreibtisch/video-stream-consistency/build/dependencies/onnxruntime/include -isystem /usr/include/qt -isystem /usr/include/qt/QtCore -isystem /usr/lib/qt/mkspecs/linux-g++ -isystem /usr/include/qt/QtWidgets -isystem /usr/include/qt/QtGui -std=gnu++20 -fPIC -MD -MT CMakeFiles/FlowVideoConsistency.dir/src/decoding/ffmpeg.cpp.o -MF CMakeFiles/FlowVideoConsistency.dir/src/decoding/ffmpeg.cpp.o.d -o CMakeFiles/FlowVideoConsistency.dir/src/decoding/ffmpeg.cpp.o -c /home/user/Schreibtisch/video-stream-consistency/src/decoding/ffmpeg.cpp
In Datei, eingebunden von /usr/include/libavutil/avutil.h:301,
                 von /home/user/Schreibtisch/video-stream-consistency/src/decoding/ffmpeg.h:9,
                 von /home/user/Schreibtisch/video-stream-consistency/src/decoding/ffmpeg.cpp:4:
/usr/include/libavutil/common.h:30:2: Fehler: #error missing -D__STDC_CONSTANT_MACROS / #define __STDC_CONSTANT_MACROS
   30 | #error missing -D__STDC_CONSTANT_MACROS / #define __STDC_CONSTANT_MACROS
      |  ^~~~~
make[2]: *** [CMakeFiles/FlowVideoConsistency.dir/build.make:266: CMakeFiles/FlowVideoConsistency.dir/src/decoding/ffmpeg.cpp.o] Fehler 1`

I'm having a go at building it on windows, here's hoping!

**Comment by MaxReimann** [comment]
For the build error you are posting I assume this is on Ubuntu? I've built mine one Ubuntu 18.04. Could you try adding `set(CMAKE_CXX_FLAGS "-D__STDC_CONSTANT_MACROS")` to the cmakelists after the set(cmake_Cxx_standard) ?

It could be related to the libav version as well, on my Ubuntu system I am using these package versions (output from apt list):

```libavcodec-dev/bionic-updates,bionic-security,now 7:3.4.11-0ubuntu0.1 amd64 [installed,automatic]
libavcodec-extra/bionic-updates,bionic-updates,bionic-security,bionic-security 7:3.4.11-0ubuntu0.1 all
libavcodec-extra57/bionic-updates,bionic-security 7:3.4.11-0ubuntu0.1 amd64
libavcodec57/bionic-updates,bionic-security,now 7:3.4.11-0ubuntu0.1 amd64 [installed,automatic]
libavdevice-dev/bionic-updates,bionic-security,now 7:3.4.11-0ubuntu0.1 amd64 [installed]
libavdevice57/bionic-updates,bionic-security,now 7:3.4.11-0ubuntu0.1 amd64 [installed,automatic]
libavfilter-dev/bionic-updates,bionic-security,now 7:3.4.11-0ubuntu0.1 amd64 [installed]
libavfilter-extra/bionic-updates,bionic-updates,bionic-security,bionic-security 7:3.4.11-0ubuntu0.1 all
libavfilter-extra6/bionic-updates,bionic-security 7:3.4.11-0ubuntu0.1 amd64
libavfilter6/bionic-updates,bionic-security,now 7:3.4.11-0ubuntu0.1 amd64 [installed,automatic]
libavformat-dev/bionic-updates,bionic-security,now 7:3.4.11-0ubuntu0.1 amd64 [installed,automatic]
libavformat57/bionic-updates,bionic-security,now 7:3.4.11-0ubuntu0.1 amd64 [installed,automatic]
```


My expectation would be that building in ubuntu and docker should both work equally well and I'd suggest trying those first, windows I tested with an early version long time ago but I don't have a test setup for that at the moment, and WSL I haven't tested at all.

**Comment by callanrocks** [comment]
I got it to build in windows! Not sure if it was that extra line in the cmake file or some more fiddling I did. Ubuntu still wasn't playing nice.

Unfortunately it's still not working, both CLI and GUI failing at the first frame simply saying abort() has been called.

The only information I was getting in the prompt:

```
`QWindowsWindow::setGeometry: Unable to set geometry 120x30+856+436 (frame: 136x69+848+405) on QWidgetWindow/"VideoOpenWidgetClassWindow" on "\\.\DISPLAY1". Resulting geometry: 140x161+856+436 (frame: 156x200+848+405) margins: 8, 31, 8, 8 minimum size: 140x161 MINMAXINFO maxSize=0,0 maxpos=0,0 mintrack=156,200 maxtrack=0,0)
Flow forward parameters: 640 360 3
Info: not downsampling flow. Set FLOWDOWNSCALE=x to set the downsampling factor.`
```

This sort of thing is way out of my experience so apologies if I'm missing something simple that should be making this just work.

**Comment by MaxReimann** [comment]
I haven't done any comprehensive testing on different system setups, so it's to be expected that there may be issues on some. The first message (unable to set geometry) is already weird by itself, but probably not the issue.

To effectively help you, can you can tell me
- your hardware & software stack (which windows version, what GPU do you have, which CUDA version are you running)
- the command you are running. I would suggest running the CLI with an image folder input and output for starters (e.g. ` ./FlowVideoConsistency -c pwcnet-light originalFrames processedFrames stabilizedFrames` ) as this doesn't require ffmpeg/libav
- if you can run the program using a debugger to determine the point where the abort is thrown would be super helpful

**Comment by callanrocks** [comment]
Took a bit longer getting back here than I intended. Ubuntu still isn't play nice unfortunately.

Running Windows 11, a 3090 and I've used a few different CUDA versions.

I managed to get it build in Windows but it was having some dependency related issues, which I think is just related to the build script pointing to the wrong folders and not finding things in the right location?

**Comment by MaxReimann** [comment]
Hello callan, unfortunately I do not have a windows with cuda GPU on hand for testing right now. Did you get it to work? Was the error related to this issue https://github.com/MaxReimann/video-stream-consistency/issues/1 ?

**Comment by aditya-raj0** [comment]
i have built it in ubuntu but running ./FlowVideoConsistency -c pwcnet-light originalFrames processedFrames stabilizedFrames produces segfaults in the char_to_cuda_float_image function

**Comment by MaxReimann** [comment]
Hello @aditya-raj0 please open a new issue for this, running the command with gdb to get a backtrace

**Comment by aditya-raj0** [comment]
this is the backtrace:

Thread 1 "FlowVideoConsis" received signal SIGSEGV, Segmentation fault.
0x00007fffa867df90 in ?? () from /lib/x86_64-linux-gnu/libcuda.so.1
(gdb) bt
#0  0x00007fffa867df90 in  () at /lib/x86_64-linux-gnu/libcuda.so.1
#1  0x00007fffa872011a in  () at /lib/x86_64-linux-gnu/libcuda.so.1
#2  0x00007fffa8870e3e in  () at /lib/x86_64-linux-gnu/libcuda.so.1
#3  0x00007fffa88729dc in  () at /lib/x86_64-linux-gnu/libcuda.so.1
#4  0x00007fffa89cfbb9 in  () at /lib/x86_64-linux-gnu/libcuda.so.1
#5  0x00007fffa862e546 in  () at /lib/x86_64-linux-gnu/libcuda.so.1
#6  0x00007fffa89aa9a0 in  () at /lib/x86_64-linux-gnu/libcuda.so.1
#7  0x00007fffa8628b82 in  () at /lib/x86_64-linux-gnu/libcuda.so.1
#8  0x00007fffa87d7c2e in  () at /lib/x86_64-linux-gnu/libcuda.so.1
#9  0x00005555556079b1 in libcudart_static_e760a7280bc1af45ef561886abc194823c5edadb ()
#10 0x00005555555d3c3a in libcudart_static_901c335edfe2e89188fa6b8fe3e2a2194ad05bff ()
#11 0x000055555562f4e9 in cudaMemcpy ()
#12 0x0000555555576392 in char_to_cuda_float_image(unsigned char*, unsigned long, GPUImage&) ()
#13 0x0000555555575e72 in GPUImage::copyFromQImage(QImage const&) ()
#14 0x00005555555845b9 in imageToGPU(QImage const&) ()
#15 0x0000555555585a4c in FileStabilizer::loadFrame(int) ()
#16 0x000055555558d036 in VideoStabilizer::preloadProcessedFrames() ()
#17 0x0000555555585d93 in FileStabilizer::stabilizeAll() ()
#18 0x00005555555c9fe2 in main ()
(gdb)
