### ISSUE TITLE
Segfault when using ./FlowVideoConsistencyPlayer

### ISSUE THREAD

**Issue by eayumi** [MaxReimann/video-stream-consistency#4]
Hi. I was trying to run the FlowVideoConsistencyPlayer but got the following Segfault, as soon as I spedify the oirginal and stylized video and press "start". What am I doing wrong?

```
Flow forward parameters: 1024 1024 3
The value of FLOWDOWNSCALE is 2
InferenceModelVariant session initializing...
2024-04-03 13:58:28.619077840 [W:onnxruntime:VideoFlowConsistency, schema_registry.cc:78 RegisterOpSchemaInternal] Trying to register schema with name Correlation (domain: custom version: 1) from file custom op registered at runtime line 0, but it is already registered from file custom op registered at runtime line 0

2024-04-03 13:58:28.619096854 [W:onnxruntime:VideoFlowConsistency, schema_registry.cc:78 RegisterOpSchemaInternal] Trying to register schema with name Warp (domain: custom version: 1) from file custom op registered at runtime line 0, but it is already registered from file custom op registered at runtime line 0

2024-04-03 13:58:28.670297935 [W:onnxruntime:, session_state.cc:1030 VerifyEachNodeIsAssignedToAnEp] Some nodes were not assigned to the preferred execution providers which may or may not have an negative impact on performance. e.g. ORT explicitly assigns shape related ops to CPU to improve perf.
2024-04-03 13:58:28.670313075 [W:onnxruntime:, session_state.cc:1032 VerifyEachNodeIsAssignedToAnEp] Rerunning with verbose output on a non-minimal build will show node assignments.
InferenceModelVariant session initialized. It took 477ms
InferenceModelVariant session initializing...
2024-04-03 13:58:29.096709091 [W:onnxruntime:VideoFlowConsistency, schema_registry.cc:78 RegisterOpSchemaInternal] Trying to register schema with name Correlation (domain: custom version: 1) from file custom op registered at runtime line 0, but it is already registered from file custom op registered at runtime line 0

2024-04-03 13:58:29.096730536 [W:onnxruntime:VideoFlowConsistency, schema_registry.cc:78 RegisterOpSchemaInternal] Trying to register schema with name Warp (domain: custom version: 1) from file custom op registered at runtime line 0, but it is already registered from file custom op registered at runtime line 0

2024-04-03 13:58:29.110675114 [W:onnxruntime:, session_state.cc:1030 VerifyEachNodeIsAssignedToAnEp] Some nodes were not assigned to the preferred execution providers which may or may not have an negative impact on performance. e.g. ORT explicitly assigns shape related ops to CPU to improve perf.
2024-04-03 13:58:29.110689980 [W:onnxruntime:, session_state.cc:1032 VerifyEachNodeIsAssignedToAnEp] Rerunning with verbose output on a non-minimal build will show node assignments.
InferenceModelVariant session initialized. It took 16ms
Frame size: 1024 1024
VideoFilterer::init_filters: video_size=1024x1024:pix_fmt=0:time_base=1/15360:pixel_aspect=0/1
VideoFilterer::init_filters: video_size=1024x1024:pix_fmt=0:time_base=1/15360:pixel_aspect=0/1

Segmentation fault (core dumped)
```
`

**Comment by maxxar92** [comment]
Does running the CLI command work, e.g.
`Usage: ./FlowVideoConsistency -c pwcnet-light test/input.mp4  test/processed.mp4 test/output`
?

**Comment by MaxReimann** [comment]
Does running the CLI command work, e.g.
 ./FlowVideoConsistency -c pwcnet-light test/input.mp4  test/processed.mp4 test/output
?

**Comment by eayumi** [comment]
Yes, it does

**Comment by MaxReimann** [comment]
Hm, ok can you run the program with gdb (`gdb --args FlowVideoConsistencyPlayer`) and post the stacktrace of the segmentation fault?

**Comment by eayumi** [comment]
```
r
Starting program: /home/eayumi/Developer/post_processing/VSC/build/FlowVideoConsistencyPlayer 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffe5ca9000 (LWP 3625486)]
[New Thread 0x7fffdffff000 (LWP 3625603)]
[New Thread 0x7fffdf7fe000 (LWP 3625604)]
[New Thread 0x7fffdeffd000 (LWP 3625605)]
[New Thread 0x7fffca849000 (LWP 3625607)]
[New Thread 0x7fffc9df1000 (LWP 3625725)]
[New Thread 0x7fffc95f0000 (LWP 3625726)]
[New Thread 0x7fffc8def000 (LWP 3625727)]
[New Thread 0x7fffbbfff000 (LWP 3625728)]
[New Thread 0x7fffbb7fe000 (LWP 3625729)]
[New Thread 0x7fffbaffd000 (LWP 3625730)]
[New Thread 0x7fffba7fc000 (LWP 3625731)]
[New Thread 0x7fffb9ffb000 (LWP 3625732)]
[New Thread 0x7fffb97fa000 (LWP 3625735)]
[Thread 0x7fffc95f0000 (LWP 3625726) exited]
[Thread 0x7fffbb7fe000 (LWP 3625729) exited]
[Thread 0x7fffbaffd000 (LWP 3625730) exited]
[Thread 0x7fffc8def000 (LWP 3625727) exited]
[Thread 0x7fffba7fc000 (LWP 3625731) exited]
[Thread 0x7fffc9df1000 (LWP 3625725) exited]
[New Thread 0x7fffc9df1000 (LWP 3625852)]
[Thread 0x7fffc9df1000 (LWP 3625852) exited]
[New Thread 0x7fffc9df1000 (LWP 3625853)]
[Thread 0x7fffbbfff000 (LWP 3625728) exited]
[New Thread 0x7fffbbfff000 (LWP 3625970)]
[New Thread 0x7fffba7fc000 (LWP 3625971)]
[New Thread 0x7fffc8def000 (LWP 3625972)]
[New Thread 0x7fffbaffd000 (LWP 3625973)]
[Thread 0x7fffc8def000 (LWP 3625972) exited]
[Thread 0x7fffbbfff000 (LWP 3625970) exited]
[Thread 0x7fffba7fc000 (LWP 3625971) exited]
[Thread 0x7fffc9df1000 (LWP 3625853) exited]
[New Thread 0x7fffc9df1000 (LWP 3626090)]
[Detaching after fork from child process 3626091]
[New Thread 0x7fffba7fc000 (LWP 3626092)]
[New Thread 0x7fffbbfff000 (LWP 3626093)]
[New Thread 0x7fffc8def000 (LWP 3626094)]
Flow forward parameters: 512 512 3
Info: not downsampling flow. Set FLOWDOWNSCALE=x to set the downsampling factor.
InferenceModelVariant session initializing...
2024-04-03 14:32:16.312431945 [W:onnxruntime:VideoFlowConsistency, schema_registry.cc:78 RegisterOpSchemaInternal] Trying to register schema with name Correlation (domain: custom version: 1) from file custom op registered at runtime line 0, but it is already registered from file custom op registered at runtime line 0

2024-04-03 14:32:16.312451009 [W:onnxruntime:VideoFlowConsistency, schema_registry.cc:78 RegisterOpSchemaInternal] Trying to register schema with name Warp (domain: custom version: 1) from file custom op registered at runtime line 0, but it is already registered from file custom op registered at runtime line 0

2024-04-03 14:32:16.380647161 [W:onnxruntime:, session_state.cc:1030 VerifyEachNodeIsAssignedToAnEp] Some nodes were not assigned to the preferred execution providers which may or may not have an negative impact on performance. e.g. ORT explicitly assigns shape related ops to CPU to improve perf.
2024-04-03 14:32:16.380666780 [W:onnxruntime:, session_state.cc:1032 VerifyEachNodeIsAssignedToAnEp] Rerunning with verbose output on a non-minimal build will show node assignments.
InferenceModelVariant session initialized. It took 575ms
InferenceModelVariant session initializing...
2024-04-03 14:32:16.888055888 [W:onnxruntime:VideoFlowConsistency, schema_registry.cc:78 RegisterOpSchemaInternal] Trying to register schema with name Correlation (domain: custom version: 1) from file custom op registered at runtime line 0, but it is already registered from file custom op registered at runtime line 0

2024-04-03 14:32:16.888073854 [W:onnxruntime:VideoFlowConsistency, schema_registry.cc:78 RegisterOpSchemaInternal] Trying to register schema with name Warp (domain: custom version: 1) from file custom op registered at runtime line 0, but it is already registered from file custom op registered at runtime line 0

2024-04-03 14:32:16.902762457 [W:onnxruntime:, session_state.cc:1030 VerifyEachNodeIsAssignedToAnEp] Some nodes were not assigned to the preferred execution providers which may or may not have an negative impact on performance. e.g. ORT explicitly assigns shape related ops to CPU to improve perf.
2024-04-03 14:32:16.902789483 [W:onnxruntime:, session_state.cc:1032 VerifyEachNodeIsAssignedToAnEp] Rerunning with verbose output on a non-minimal build will show node assignments.
InferenceModelVariant session initialized. It took 16ms
Frame size: 512 512
VideoFilterer::init_filters: video_size=512x512:pix_fmt=0:time_base=1/10240:pixel_aspect=0/1
[New Thread 0x7fffb882b000 (LWP 3626212)]
[New Thread 0x7fff815b2000 (LWP 3626213)]
[New Thread 0x7fff80db1000 (LWP 3626214)]
[New Thread 0x7fff22d34000 (LWP 3626215)]
[New Thread 0x7fff22533000 (LWP 3626216)]
[New Thread 0x7fff21d32000 (LWP 3626217)]
[New Thread 0x7fff21531000 (LWP 3626218)]
[New Thread 0x7fff20d30000 (LWP 3626219)]
VideoFilterer::init_filters: video_size=512x512:pix_fmt=0:time_base=1/10240:pixel_aspect=0/1
[New Thread 0x7fff11fff000 (LWP 3626220)]
[New Thread 0x7fff117fe000 (LWP 3626221)]
[New Thread 0x7fff10ffd000 (LWP 3626222)]
[New Thread 0x7fff09fff000 (LWP 3626223)]
[New Thread 0x7fff097fe000 (LWP 3626224)]
[New Thread 0x7fff08ffd000 (LWP 3626225)]
[New Thread 0x7ffefe6a3000 (LWP 3626226)]
[New Thread 0x7ffefdea2000 (LWP 3626227)]
"/home/eayumi/Developer/evaluation/evaluation_visual/test_aziz.mp4"
--Type <RET> for more, q to quit, c to continue without paging--

Thread 22 "Thread (pooled)" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffc9df1000 (LWP 3626090)]
QString::QString (other=..., this=0x7fffc9dec410, this@entry=0x7fffc9dec408) at ../../include/QtCore/../../src/corelib/text/qstring.h:1094
1094	../../include/QtCore/../../src/corelib/text/qstring.h: No such file or directory.
(gdb) bt
#0  QString::QString(QString const&) (other=..., this=0x7fffc9dec410, this@entry=0x7fffc9dec408) at ../../include/QtCore/../../src/corelib/text/qstring.h:1094
#1  QDir::fromNativeSeparators(QString const&) (pathName=...) at io/qdir.cpp:968
#2  0x00007ffff6408ab3 in QFileInfoPrivate::QFileInfoPrivate(QString const&) (file=..., this=0x7fff1dd9e140) at io/qfileinfo_p.h:104
#3  QFileInfo::QFileInfo(QString const&) (this=0x7fffc9dec490, file=...) at io/qfileinfo.cpp:347
#4  0x0000555555592e22 in StreamStabilizer::StreamStabilizer(QDir, QDir, std::optional<QString>, std::optional<QString>, int, int, int, bool) ()
#5  0x00005555555b4aae in VideoPlayer::createStreamStabilizer(QString, QString) ()
#6  0x00005555555b4ffe in VideoPlayer::openFile(QString, QString)::{lambda()#1}::operator()() const ()
#7  0x00005555555b676e in QtConcurrent::StoredFunctorCall0<void, VideoPlayer::openFile(QString, QString)::{lambda()#1}>::runFunctor() ()
#8  0x00005555555b6b1b in QtConcurrent::RunFunctionTask<void>::run() ()
#9  0x00007ffff62f766a in QThreadPoolThread::run() (this=0x555555ba2b90) at thread/qthreadpool.cpp:100
#10 0x00007ffff62f3b35 in QThreadPrivate::start(void*) (arg=0x555555ba2b90) at thread/qthread_unix.cpp:329
#11 0x00007ffff34b4609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#12 0x00007ffff3085353 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
(gdb) c
Continuing.
Couldn't get registers: No such process.
Couldn't get registers: No such process.
(gdb) [Thread 0x7ffefdea2000 (LWP 3626227) exited]
[Thread 0x7ffefe6a3000 (LWP 3626226) exited]
[Thread 0x7fff08ffd000 (LWP 3626225) exited]
[Thread 0x7fff097fe000 (LWP 3626224) exited]
[Thread 0x7fff09fff000 (LWP 3626223) exited]
[Thread 0x7fff10ffd000 (LWP 3626222) exited]
[Thread 0x7fff117fe000 (LWP 3626221) exited]
[Thread 0x7fff11fff000 (LWP 3626220) exited]
[Thread 0x7fff20d30000 (LWP 3626219) exited]
[Thread 0x7fff21531000 (LWP 3626218) exited]
[Thread 0x7fff21d32000 (LWP 3626217) exited]
[Thread 0x7fff22533000 (LWP 3626216) exited]
[Thread 0x7fff22d34000 (LWP 3626215) exited]
[Thread 0x7fff80db1000 (LWP 3626214) exited]
[Thread 0x7fff815b2000 (LWP 3626213) exited]
[Thread 0x7fffb882b000 (LWP 3626212) exited]
[Thread 0x7fffc8def000 (LWP 3626094) exited]
[Thread 0x7fffbbfff000 (LWP 3626093) exited]
[Thread 0x7fffba7fc000 (LWP 3626092) exited]
[Thread 0x7fffbaffd000 (LWP 3625973) exited]
[Thread 0x7fffb97fa000 (LWP 3625735) exited]
[Thread 0x7fffb9ffb000 (LWP 3625732) exited]
[Thread 0x7fffca849000 (LWP 3625607) exited]
[Thread 0x7fffdeffd000 (LWP 3625605) exited]
[Thread 0x7fffdf7fe000 (LWP 3625604) exited]
[Thread 0x7fffdffff000 (LWP 3625603) exited]
[Thread 0x7fffe5ca9000 (LWP 3625486) exited]
[Thread 0x7fffe7027000 (LWP 3625250) exited]

Program terminated with signal SIGSEGV, Segmentation fault.
The program no longer exists.
```

**Comment by MaxReimann** [comment]
Thank you. I pushed a quickfix, please report if this solves the issue. Otherwise I will need to dig deeper when I get the time

**Comment by eayumi** [comment]
It works now! Thank you so much!!
